### ISSUE TITLE
Very panicky API, lots of `.expect` and `.unwrap`.

### ISSUE THREAD

**Issue by cristicbz** [booyaa/wifiscanner#1]
Tried this on Linux (which I since figured is not meant to be supported yet), but the failure mode is a `panic`. I noticed that all operations which may fail are `unwrap`'d.

Would be nice to have a `wifiscanner::Error` type and return a `Result<Vec<Wifi>>` instead.

(thanks for the crate, hope to get this on Linux!)

**Comment by booyaa** [comment]
Just released [0.2.0](https://github.com/booyaa/wifiscanner/commit/b623f8611f9f56e44717ea8fe44cc732d9abb305), less panicky and returning a Result<Vec<Wifi>> with a Error if run not run on OS X. Still need to fix the .expects when finding data boundaries.

Will keep this issue open until I've tidied up and refactor some more.

**Comment by booyaa** [comment]
Slow improving this with [0.3.0](f649195f7d6c4381563317849910916fea02da51) still room for improvement. The lib needs breaking up.

**Comment by Boscop** [comment]
Any updates on this?
