### ISSUE TITLE
Licence shows up as non-standard on crates.io

### ISSUE THREAD

**Issue by cristicbz** [booyaa/wifiscanner#2]
It looks like this is licenced under Apache 2.0, but Cargo doesn't pick up on it unless specified in the manifest. That's why it shows up as "license: non-standard" on crates.io . You may want to add a

```
license = "Apache-2.0"
```

or (for GPL compatibility):

```
license = "MIT/Apache-2.0"
```

under the `[package]` section in `Cargo.toml`.

**Comment by booyaa** [comment]
i tried using the license-file, but it appears to have ignored or failed to parse it. i've updated the Cargo.tom to use the `license` instead.

**Comment by booyaa** [comment]
Closing as resolved https://github.com/booyaa/wifiscanner/commit/b623f8611f9f56e44717ea8fe44cc732d9abb305
