### ISSUE TITLE
Update the README.md to replace the Travis build badge with the GitHub Action equivalent

### ISSUE THREAD

**Issue by booyaa** [booyaa/wifiscanner#38]
Hint: the URL format is `https://github.com/<user>/<repo>/workflows/<name of workflow>/badge.svg`

## Acceptance criteria

* does not break the build (the CI GitHub Action Workflow)
* does not change the formatting of the README.md dramatically i.e. no auto-formatting, please

I will provide guidance and help (including how to use Git and/or GitHub) just @ me.

**Comment by vmfunc** [comment]
what's your workflow name @booyaa ?
