### ISSUE TITLE
Enable automatic publishing to crates.io on merge to main branch

### ISSUE THREAD

**Issue by booyaa** [booyaa/wifiscanner#39]
## Acceptance criteria

- must be part of the existing CI GitHub Workflow
- should use GitHub Action secrets (no hard coding of API token)
- should generate GitHub releases

I'll need to work with you to add the secret token, so please @ me when you're ready to test

**Comment by reime005** [comment]
@booyaa you can test it, you just need to add the CRATES_TOKEN and then create a tag, which should trigger a deploy & release on github

**Comment by reime005** [comment]
@booyaa could you add the "hacktoberfest" topic to the repo?

**Comment by booyaa** [comment]
@reime005 done, sorry for the delay I'll be reviewing this PR (thank you) this weekend.
