### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by booyaa** [booyaa/wifiscanner#5]
using `netsh.exe wlan show networks mode=Bssid`

if you can help please attach sample output (as text no images) as a comment.

**Comment by Boscop** [comment]
I'm interested in Windows support.
[Here](http://pastebin.centos.org/292376/6362889/raw/) is the output of that command, (I modified some MAC addresses and SSIDs for privacy reasons but didn't modify the format).
Notice that it contains the output of all two enabled Wifi Interfaces. One has a better antenna than the other.

**Comment by Boscop** [comment]
I just noticed that the paste expired, did you download it before it expired?

**Comment by Boscop** [comment]
I made a new scan, [here](http://pastebin.centos.org/408136/50939875/raw/).
Nothing is stopping you from adding windows support now :)

**Comment by booyaa** [comment]
I don't have the time, but I'll be adding a contributors.md so others can step in to help. Also might be a good idea to stick it on something more permanent like gist?

**Comment by Boscop** [comment]
I put it in a gist [here](https://gist.github.com/Boscop/e7507935878a9e6306fb0d1d80532518) :)
