### ISSUE TITLE
`wifiscanner::scan()` returns `OK()` but empty WiFi vector

### ISSUE THREAD

**Issue by RuXBee** [booyaa/wifiscanner#56]
I have tried to run the example and the `wifiscanner::scan()` returns `OK()` without any __vector WiFi__ type.
![image](https://github.com/booyaa/wifiscanner/assets/61663837/6ed068aa-7e6c-4246-a286-a1f01a8ed1b5)

Also, I share the version of the __iw__ tool is based this __crate__.
![image](https://github.com/booyaa/wifiscanner/assets/61663837/49eb1206-00b3-4285-b76e-d289268a0a25)

Does anyone can help me? :smiley:

**Comment by unknownK19** [comment]
I tried this cammand 
`cargo run`
similarly I got empty
![Screenshot from 2023-11-12 10-32-55](https://github.com/booyaa/wifiscanner/assets/107351441/bb4bdb2e-d2f9-4de3-8222-6c523d3f213e)

And then I tried `sudo cargo run` I got it !
![Screenshot from 2023-11-12 10-35-39](https://github.com/booyaa/wifiscanner/assets/107351441/5ada48cb-08fd-4cc0-8cc5-4c5d0a0b528a)

It means WIFI scan can only work by sudo permission
